// Generated by Wrangler — extended with project bindings.

interface Env {
  DB: D1Database;
  BUCKET: R2Bucket;
  SEVADAL_CACHE: KVNamespace;
  SESSION_SECRET: string;
  BACKUP_SECRET: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_CHAT_ID: string;
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY_JWK: string;
  VAPID_SUBJECT: string;
}
